[global]
workgroup = WORKGROUP
server string = PXEForge
security = user
map to guest = Bad User

[ISOS]
path = /mount
browseable = yes
read only = no
guest ok = no
create mask = 0644
directory mask = 0755
